version: '3.8'

services:
  app:
    container_name: sms-sender-app
    image: sms-sender-app
    build:
      context: .
      dockerfile: ./build/dockerfiles/Dockerfile.app
    ports:
      - '8080:8080'
    env_file:
      - .env
    restart: on-failure
    # healthcheck:
    #   test: curl --fail -s localhost:8080/info/status || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  mjml:
    image: adrianrudnik/mjml-server
    ports:
      - 5000:80
    environment:
      - CORS=*
      - MJML_KEEP_COMMENTS=true
      - MJML_VALIDATION_LEVEL=strict
      - MJML_MINIFY=false
      - MJML_BEAUTIFY=true
