---
version: 3

tasks:
  setup:
  desc: 'Quickstart the project for running'
  cmds:
    - cp .env.example .env
    - echo "Please fill the .env file with the required values"
  silent: true

  start:
    desc: "Run the docker composefile"
    cmds:
      - echo "Starting the application with docker"
      - docker compose up --build
    silent: true
  
  start-quick:
    desc: "Run the quick starting docker composefile"
    cmds:
      - echo "Starting the application with docker"
      - docker compose -f docker-compose.quick.yml up --build
    silent: true

  gen-sqlc:
    desc: 'Generate the sql queries using sqlc'
    cmds:
      - echo "Generating the sqlc"
      - docker run --rm -v ./database:/src -w /src sqlc/sqlc generate
      - rm -rf ./src/pkg/db/gen-sqlc
      - mkdir ./src/pkg/db/gen-sqlc
      - mv ./database/generated ./src/pkg/db/gen-sqlc
    silent: true
  
  gen-embedded-api:
    desc: 'Generate the embedded json for the api'
    cmds:
      - echo "Generating the embedded json for the api"
      - docker run --rm -v ./api-spec/:/spec redocly/cli bundle openapi.yml -o openapi.json
      - mv ./api-spec/openapi.json ./src/pkg/server/handler/apihandler/embedded/openapi.json
    silent: true

  gen-api-std:
    desc: 'Generate the api wrapper interfaces for std server using oapi-codegen'
    cmds:
      - echo "Generate the api wrapper interfaces for std server using oapi-codegen"
      - oapi-codegen --config ./api-spec/server-std.cfg.yml ./api-spec/bundle.yml > ./src/pkg/server/generated/api.gen.go
    silent: true

  gen-api-types:
    desc: 'Generate the types for the api using oapi-codegen'
    cmds:
      - echo "Generating the types for the api using oapi-codegen"
      - oapi-codegen -generate types -package server ./api-spec/bundle.yml > ./src/pkg/server/generated/types.gen.go
    silent: true

  gen-api:
    desc: 'Generate the api for the server using oapi-codegen'
    cmds:
      - echo "Generating the api for the server using oapi-codegen"
      - task lint-api
      - task bundle-api
      - task gen-embedded-api
      - task gen-api-types
      - task gen-api-std
    silent: true

  lint-api:
    desc: 'Lint the api-spec using redocly'
    cmds:
      - echo "Linting the api-spec"
      - docker run --rm -v ./api-spec/:/spec redocly/cli lint openapi.yml
    silent: true

  bundle-api:
    desc: 'Bundle the api-spec using redocly'
    cmds:
      - echo "Bundling the api-spec using redocly/redoc"
      - docker run --rm -v ./api-spec/:/spec redocly/cli bundle openapi.yml -o bundle.yml
    silent: true
