openapi: 3.0.3
info:
  title: SMS Service API
  version: 1.0.0
  license:
    name: unlicensed
    url: www.example.com
servers:
  - url: /
    description: This server
paths:
  /sms:
    post:
      summary: Send a SMS with custom text
      operationId: sendSMS
      tags:
        - SMS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMSSendRequest'
      responses:
        '201':
          description: SMS send
        '400':
          description: Invalid receiver phone number supplied
      security: []
  /email:
    post:
      summary: Send an Email with custom text
      operationId: sendEmail
      tags:
        - Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailSendRequest'
      responses:
        '201':
          description: SMS send
        '400':
          description: Invalid receiver phone number supplied
      security: []
  /templates:
    post:
      summary: Add new template
      operationId: addNewTemplate
      tags:
        - template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplatePostRequest'
      responses:
        '201':
          description: Added template (name)
        '400':
          description: Invalid name supplied
      security: []
  /templates/{name}:
    get:
      summary: Get Template by Name
      operationId: getTemplateByName
      tags:
        - template
      parameters:
        - name: name
          in: path
          description: Name of template to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '400':
          description: Invalid name supplied
        '404':
          description: Can not find template (template name)
      security: []
    post:
      summary: Fill placeholders of template
      operationId: fillTemplate
      tags:
        - template
      parameters:
        - name: name
          in: path
          description: Name of template to fill
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateFillRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilledTemplateResponse'
        '400':
          description: Invalid name or data supplied
      security: []
components:
  schemas:
    SMSSendRequest:
      type: object
      properties:
        receiverPhoneNumber:
          type: string
          example: '+49123456789'
        message:
          type: string
          example: Don't forget to buy some milk!
      required:
        - receiverPhoneNumber
        - message
    EmailSendRequest:
      type: object
      properties:
        toEmail:
          type: string
          example: holmes@detective.com
        toName:
          type: string
          example: Sherlock Holmes
        subject:
          type: string
          example: New Case
        message:
          type: string
          example: Find the thief!
      required:
        - toEmail
        - toName
        - subject
        - message
    TemplatePostRequest:
      type: object
      properties:
        name:
          type: string
          example: ExampleName
        templateMJMLCode:
          type: string
          example: <mjml><mj-body><mj-section><mj-column><mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World </mj-text></mj-column></mj-section></mj-body></mjml>
      required:
        - name
        - templateMJMLCode
    Template:
      type: object
      properties:
        name:
          type: string
          example: ExampleName
        templateMJMLCode:
          type: string
          example: <mjml><mj-body><mj-section><mj-column><mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text></mj-column></mj-section></mj-body></mjml>
        data:
          type: array
          items:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                    - key
                    - value
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  example:
                    - key: firstName
                      value: Sherlock
                    - key: lastName
                      value: Holmes
      required:
        - name
        - templateMJMLCode
        - data
    TemplateFillRequest:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                    - key
                    - value
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  example:
                    - key: firstName
                      value: Sherlock
                    - key: lastName
                      value: Holmes
    FilledTemplateResponse:
      type: object
      properties:
        name:
          type: string
          example: ExampleName
        templateMJMLCode:
          type: string
          example: <mjml><mj-body><mj-section><mj-column><mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World </mj-text></mj-column></mj-section></mj-body></mjml>
      required:
        - name
        - templateMJMLCode
