openapi: 3.0.3
info:
  title: SMS Service API
  version: 1.0.0
  license:
    name: unlicensed
    url: "www.example.com"
  contact: 
    name: API Support
    email: support@example.com
    url: http://example.com
servers:
  - url: /
    description: This server
paths:
  $ref: './resources/_index.yml'
components:
  schemas: 
    $ref: './schemas/_index.yml'
tags:
  - name: SMS
    description: Everything for the SMS sending service
  - name: Email
    description: Everything for the Email sending service
  - name: PDF
    description: Everything for the PDF rendering service
  - name: APIInfo
    description: General API information
