---
get:
  tags:
    - APIInfo
  summary: Get describing html of openapi spec
  description: Retrieve the OpenAPI spec as HTML
  operationId: getOpenAPIHTML
  responses:
    '200':
      description: The rendered HTML for the OpenAPI spec
      content:
        text/html:
          schema:
            type: string
            example: '<html>...</html>'
    '400':
      description: You somehow managed to mess up the oapi html request
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'
          example:
            $ref: '../../examples/_index.yml#/ErrorExample'

  # This API has no security
  security: []
