Table emailtemplates {
  id integer [primary key, increment]
  name varchar [not null, unique]
  templ_string varchar [not null]
  is_mjml bool [not null]
  created_at timestamptz [default: `now()`]
}

Table pdftemplates {
  id integer [primary key, increment]
  name varchar [not null, unique]
  templ_string varchar [not null]
  created_at timestamptz [default: `now()`]
}

Table smstemplates {
  id integer [primary key, increment]
  name varchar [not null, unique]
  templ_string varchar [not null]
  created_at timestamptz [default: `now()`]
}

Table workflows {
  id integer [primary key, increment]
  name varchar [not null, unique]
  email_templated_name varchar [not null]
  email_subject varchar [not null]
  static_attachments varchar [not null]
  templated_pdfs varchar [not null]
  created_at timestamptz [default: `now()`]
}
