Table emailtemplates {
  id integer [primary key, increment]
  name varchar [not null, unique]
  mjml_string varchar [not null]
  created_at timestamptz [default: `now()`]
}

Table pdftemplates {
  id integer [primary key, increment]
  name varchar [not null, unique]
  typst_string varchar [not null]
  created_at timestamptz [default: `now()`]
}
