-- +migrate Up

CREATE TABLE "emailtemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar unique,
  "templ_string" varchar,
  "is_mjml" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "pdftemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar unique,
  "typst_string" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "smstemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar unique,
  "templ_string" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "pdfs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar unique,
  "content" varchar,
  "created_at" timestamptz DEFAULT (now())
);
