-- +migrate Up

CREATE TABLE "emailtemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar unique,
  "mjml_string" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "pdftemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar unique,
  "typst_string" varchar,
  "created_at" timestamptz DEFAULT (now())
);
