type: object
properties:
  name:
    type: string
    example: "ExampleName"
  requiredInputs:
    type: object
    properties:
      toEmail:
        type: string
        example: "example@example.com"
      toName:
        type: string
        example: "exampleName"
      emailTemplate:
        type: object
        properties:
          templateName:
            type: string
            example: "exampleTemplate"
          placeholders:
            type: array
            items:
              type: string
            example: ["key1", "key2"]
        required:
          - templateName
          - placeholders
      pdfTemplate:
        type: object
        properties:
          templateName:
            type: string
            example: "exampleTemplate"
          placeholders:
            type: array
            items:
              type: string
            example: ["key1", "key2"]
        required:
          - templateName
          - placeholders
    required:
      - toEmail
      - toName
      - emailTemplate
required:
  - name
  - requiredInputs
