
linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - staticcheck
    - stylecheck
    - unused
    - whitespace


linters-settings:
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

issues:
  exclude-rules:
    - linters:
      - stylecheck
      text: "ST1003:"

run:
  timeout: 5m
